// Compact element table. cat = category, st = state at 25°C.
// Categories: am=alkali metal, ae=alkaline earth, tm=transition metal,
// pm=post-transition metal, ml=metalloid, nm=nonmetal, ha=halogen,
// ng=noble gas, la=lanthanide, ac=actinide, un=unknown.
// Column/row are 1-based positions in the standard 18-col layout.

export const ELEMENTS = [
  { z:  1, sym: 'H',  name: 'Hydrogen',     mass:   1.008, col:  1, row: 1, cat: 'nm', st: 'gas' },
  { z:  2, sym: 'He', name: 'Helium',       mass:   4.003, col: 18, row: 1, cat: 'ng', st: 'gas' },
  { z:  3, sym: 'Li', name: 'Lithium',      mass:   6.94,  col:  1, row: 2, cat: 'am', st: 'solid' },
  { z:  4, sym: 'Be', name: 'Beryllium',    mass:   9.012, col:  2, row: 2, cat: 'ae', st: 'solid' },
  { z:  5, sym: 'B',  name: 'Boron',        mass:  10.81,  col: 13, row: 2, cat: 'ml', st: 'solid' },
  { z:  6, sym: 'C',  name: 'Carbon',       mass:  12.011, col: 14, row: 2, cat: 'nm', st: 'solid' },
  { z:  7, sym: 'N',  name: 'Nitrogen',     mass:  14.007, col: 15, row: 2, cat: 'nm', st: 'gas' },
  { z:  8, sym: 'O',  name: 'Oxygen',       mass:  15.999, col: 16, row: 2, cat: 'nm', st: 'gas' },
  { z:  9, sym: 'F',  name: 'Fluorine',     mass:  18.998, col: 17, row: 2, cat: 'ha', st: 'gas' },
  { z: 10, sym: 'Ne', name: 'Neon',         mass:  20.18,  col: 18, row: 2, cat: 'ng', st: 'gas' },
  { z: 11, sym: 'Na', name: 'Sodium',       mass:  22.99,  col:  1, row: 3, cat: 'am', st: 'solid' },
  { z: 12, sym: 'Mg', name: 'Magnesium',    mass:  24.305, col:  2, row: 3, cat: 'ae', st: 'solid' },
  { z: 13, sym: 'Al', name: 'Aluminium',    mass:  26.982, col: 13, row: 3, cat: 'pm', st: 'solid' },
  { z: 14, sym: 'Si', name: 'Silicon',      mass:  28.085, col: 14, row: 3, cat: 'ml', st: 'solid' },
  { z: 15, sym: 'P',  name: 'Phosphorus',   mass:  30.974, col: 15, row: 3, cat: 'nm', st: 'solid' },
  { z: 16, sym: 'S',  name: 'Sulfur',       mass:  32.06,  col: 16, row: 3, cat: 'nm', st: 'solid' },
  { z: 17, sym: 'Cl', name: 'Chlorine',     mass:  35.45,  col: 17, row: 3, cat: 'ha', st: 'gas' },
  { z: 18, sym: 'Ar', name: 'Argon',        mass:  39.948, col: 18, row: 3, cat: 'ng', st: 'gas' },
  { z: 19, sym: 'K',  name: 'Potassium',    mass:  39.098, col:  1, row: 4, cat: 'am', st: 'solid' },
  { z: 20, sym: 'Ca', name: 'Calcium',      mass:  40.078, col:  2, row: 4, cat: 'ae', st: 'solid' },
  { z: 21, sym: 'Sc', name: 'Scandium',     mass:  44.956, col:  3, row: 4, cat: 'tm', st: 'solid' },
  { z: 22, sym: 'Ti', name: 'Titanium',     mass:  47.867, col:  4, row: 4, cat: 'tm', st: 'solid' },
  { z: 23, sym: 'V',  name: 'Vanadium',     mass:  50.942, col:  5, row: 4, cat: 'tm', st: 'solid' },
  { z: 24, sym: 'Cr', name: 'Chromium',     mass:  51.996, col:  6, row: 4, cat: 'tm', st: 'solid' },
  { z: 25, sym: 'Mn', name: 'Manganese',    mass:  54.938, col:  7, row: 4, cat: 'tm', st: 'solid' },
  { z: 26, sym: 'Fe', name: 'Iron',         mass:  55.845, col:  8, row: 4, cat: 'tm', st: 'solid' },
  { z: 27, sym: 'Co', name: 'Cobalt',       mass:  58.933, col:  9, row: 4, cat: 'tm', st: 'solid' },
  { z: 28, sym: 'Ni', name: 'Nickel',       mass:  58.693, col: 10, row: 4, cat: 'tm', st: 'solid' },
  { z: 29, sym: 'Cu', name: 'Copper',       mass:  63.546, col: 11, row: 4, cat: 'tm', st: 'solid' },
  { z: 30, sym: 'Zn', name: 'Zinc',         mass:  65.38,  col: 12, row: 4, cat: 'tm', st: 'solid' },
  { z: 31, sym: 'Ga', name: 'Gallium',      mass:  69.723, col: 13, row: 4, cat: 'pm', st: 'solid' },
  { z: 32, sym: 'Ge', name: 'Germanium',    mass:  72.63,  col: 14, row: 4, cat: 'ml', st: 'solid' },
  { z: 33, sym: 'As', name: 'Arsenic',      mass:  74.922, col: 15, row: 4, cat: 'ml', st: 'solid' },
  { z: 34, sym: 'Se', name: 'Selenium',     mass:  78.971, col: 16, row: 4, cat: 'nm', st: 'solid' },
  { z: 35, sym: 'Br', name: 'Bromine',      mass:  79.904, col: 17, row: 4, cat: 'ha', st: 'liquid' },
  { z: 36, sym: 'Kr', name: 'Krypton',      mass:  83.798, col: 18, row: 4, cat: 'ng', st: 'gas' },
  { z: 37, sym: 'Rb', name: 'Rubidium',     mass:  85.468, col:  1, row: 5, cat: 'am', st: 'solid' },
  { z: 38, sym: 'Sr', name: 'Strontium',    mass:  87.62,  col:  2, row: 5, cat: 'ae', st: 'solid' },
  { z: 39, sym: 'Y',  name: 'Yttrium',      mass:  88.906, col:  3, row: 5, cat: 'tm', st: 'solid' },
  { z: 40, sym: 'Zr', name: 'Zirconium',    mass:  91.224, col:  4, row: 5, cat: 'tm', st: 'solid' },
  { z: 41, sym: 'Nb', name: 'Niobium',      mass:  92.906, col:  5, row: 5, cat: 'tm', st: 'solid' },
  { z: 42, sym: 'Mo', name: 'Molybdenum',   mass:  95.95,  col:  6, row: 5, cat: 'tm', st: 'solid' },
  { z: 43, sym: 'Tc', name: 'Technetium',   mass:  98,     col:  7, row: 5, cat: 'tm', st: 'solid' },
  { z: 44, sym: 'Ru', name: 'Ruthenium',    mass: 101.07,  col:  8, row: 5, cat: 'tm', st: 'solid' },
  { z: 45, sym: 'Rh', name: 'Rhodium',      mass: 102.906, col:  9, row: 5, cat: 'tm', st: 'solid' },
  { z: 46, sym: 'Pd', name: 'Palladium',    mass: 106.42,  col: 10, row: 5, cat: 'tm', st: 'solid' },
  { z: 47, sym: 'Ag', name: 'Silver',       mass: 107.868, col: 11, row: 5, cat: 'tm', st: 'solid' },
  { z: 48, sym: 'Cd', name: 'Cadmium',      mass: 112.414, col: 12, row: 5, cat: 'tm', st: 'solid' },
  { z: 49, sym: 'In', name: 'Indium',       mass: 114.818, col: 13, row: 5, cat: 'pm', st: 'solid' },
  { z: 50, sym: 'Sn', name: 'Tin',          mass: 118.71,  col: 14, row: 5, cat: 'pm', st: 'solid' },
  { z: 51, sym: 'Sb', name: 'Antimony',     mass: 121.76,  col: 15, row: 5, cat: 'ml', st: 'solid' },
  { z: 52, sym: 'Te', name: 'Tellurium',    mass: 127.6,   col: 16, row: 5, cat: 'ml', st: 'solid' },
  { z: 53, sym: 'I',  name: 'Iodine',       mass: 126.904, col: 17, row: 5, cat: 'ha', st: 'solid' },
  { z: 54, sym: 'Xe', name: 'Xenon',        mass: 131.293, col: 18, row: 5, cat: 'ng', st: 'gas' },
  { z: 55, sym: 'Cs', name: 'Caesium',      mass: 132.905, col:  1, row: 6, cat: 'am', st: 'solid' },
  { z: 56, sym: 'Ba', name: 'Barium',       mass: 137.327, col:  2, row: 6, cat: 'ae', st: 'solid' },
  { z: 57, sym: 'La', name: 'Lanthanum',    mass: 138.905, col:  3, row: 9, cat: 'la', st: 'solid' },
  { z: 58, sym: 'Ce', name: 'Cerium',       mass: 140.116, col:  4, row: 9, cat: 'la', st: 'solid' },
  { z: 59, sym: 'Pr', name: 'Praseodymium', mass: 140.908, col:  5, row: 9, cat: 'la', st: 'solid' },
  { z: 60, sym: 'Nd', name: 'Neodymium',    mass: 144.242, col:  6, row: 9, cat: 'la', st: 'solid' },
  { z: 61, sym: 'Pm', name: 'Promethium',   mass: 145,     col:  7, row: 9, cat: 'la', st: 'solid' },
  { z: 62, sym: 'Sm', name: 'Samarium',     mass: 150.36,  col:  8, row: 9, cat: 'la', st: 'solid' },
  { z: 63, sym: 'Eu', name: 'Europium',     mass: 151.964, col:  9, row: 9, cat: 'la', st: 'solid' },
  { z: 64, sym: 'Gd', name: 'Gadolinium',   mass: 157.25,  col: 10, row: 9, cat: 'la', st: 'solid' },
  { z: 65, sym: 'Tb', name: 'Terbium',      mass: 158.925, col: 11, row: 9, cat: 'la', st: 'solid' },
  { z: 66, sym: 'Dy', name: 'Dysprosium',   mass: 162.5,   col: 12, row: 9, cat: 'la', st: 'solid' },
  { z: 67, sym: 'Ho', name: 'Holmium',      mass: 164.93,  col: 13, row: 9, cat: 'la', st: 'solid' },
  { z: 68, sym: 'Er', name: 'Erbium',       mass: 167.259, col: 14, row: 9, cat: 'la', st: 'solid' },
  { z: 69, sym: 'Tm', name: 'Thulium',      mass: 168.934, col: 15, row: 9, cat: 'la', st: 'solid' },
  { z: 70, sym: 'Yb', name: 'Ytterbium',    mass: 173.045, col: 16, row: 9, cat: 'la', st: 'solid' },
  { z: 71, sym: 'Lu', name: 'Lutetium',     mass: 174.967, col: 17, row: 9, cat: 'la', st: 'solid' },
  { z: 72, sym: 'Hf', name: 'Hafnium',      mass: 178.49,  col:  4, row: 6, cat: 'tm', st: 'solid' },
  { z: 73, sym: 'Ta', name: 'Tantalum',     mass: 180.948, col:  5, row: 6, cat: 'tm', st: 'solid' },
  { z: 74, sym: 'W',  name: 'Tungsten',     mass: 183.84,  col:  6, row: 6, cat: 'tm', st: 'solid' },
  { z: 75, sym: 'Re', name: 'Rhenium',      mass: 186.207, col:  7, row: 6, cat: 'tm', st: 'solid' },
  { z: 76, sym: 'Os', name: 'Osmium',       mass: 190.23,  col:  8, row: 6, cat: 'tm', st: 'solid' },
  { z: 77, sym: 'Ir', name: 'Iridium',      mass: 192.217, col:  9, row: 6, cat: 'tm', st: 'solid' },
  { z: 78, sym: 'Pt', name: 'Platinum',     mass: 195.084, col: 10, row: 6, cat: 'tm', st: 'solid' },
  { z: 79, sym: 'Au', name: 'Gold',         mass: 196.967, col: 11, row: 6, cat: 'tm', st: 'solid' },
  { z: 80, sym: 'Hg', name: 'Mercury',      mass: 200.592, col: 12, row: 6, cat: 'tm', st: 'liquid' },
  { z: 81, sym: 'Tl', name: 'Thallium',     mass: 204.38,  col: 13, row: 6, cat: 'pm', st: 'solid' },
  { z: 82, sym: 'Pb', name: 'Lead',         mass: 207.2,   col: 14, row: 6, cat: 'pm', st: 'solid' },
  { z: 83, sym: 'Bi', name: 'Bismuth',      mass: 208.98,  col: 15, row: 6, cat: 'pm', st: 'solid' },
  { z: 84, sym: 'Po', name: 'Polonium',     mass: 209,     col: 16, row: 6, cat: 'pm', st: 'solid' },
  { z: 85, sym: 'At', name: 'Astatine',     mass: 210,     col: 17, row: 6, cat: 'ha', st: 'solid' },
  { z: 86, sym: 'Rn', name: 'Radon',        mass: 222,     col: 18, row: 6, cat: 'ng', st: 'gas' },
  { z: 87, sym: 'Fr', name: 'Francium',     mass: 223,     col:  1, row: 7, cat: 'am', st: 'solid' },
  { z: 88, sym: 'Ra', name: 'Radium',       mass: 226,     col:  2, row: 7, cat: 'ae', st: 'solid' },
  { z: 89, sym: 'Ac', name: 'Actinium',     mass: 227,     col:  3, row: 10, cat: 'ac', st: 'solid' },
  { z: 90, sym: 'Th', name: 'Thorium',      mass: 232.038, col:  4, row: 10, cat: 'ac', st: 'solid' },
  { z: 91, sym: 'Pa', name: 'Protactinium', mass: 231.036, col:  5, row: 10, cat: 'ac', st: 'solid' },
  { z: 92, sym: 'U',  name: 'Uranium',      mass: 238.029, col:  6, row: 10, cat: 'ac', st: 'solid' },
  { z: 93, sym: 'Np', name: 'Neptunium',    mass: 237,     col:  7, row: 10, cat: 'ac', st: 'solid' },
  { z: 94, sym: 'Pu', name: 'Plutonium',    mass: 244,     col:  8, row: 10, cat: 'ac', st: 'solid' },
  { z: 95, sym: 'Am', name: 'Americium',    mass: 243,     col:  9, row: 10, cat: 'ac', st: 'solid' },
  { z: 96, sym: 'Cm', name: 'Curium',       mass: 247,     col: 10, row: 10, cat: 'ac', st: 'solid' },
  { z: 97, sym: 'Bk', name: 'Berkelium',    mass: 247,     col: 11, row: 10, cat: 'ac', st: 'solid' },
  { z: 98, sym: 'Cf', name: 'Californium',  mass: 251,     col: 12, row: 10, cat: 'ac', st: 'solid' },
  { z: 99, sym: 'Es', name: 'Einsteinium',  mass: 252,     col: 13, row: 10, cat: 'ac', st: 'solid' },
  { z:100, sym: 'Fm', name: 'Fermium',      mass: 257,     col: 14, row: 10, cat: 'ac', st: 'unknown' },
  { z:101, sym: 'Md', name: 'Mendelevium',  mass: 258,     col: 15, row: 10, cat: 'ac', st: 'unknown' },
  { z:102, sym: 'No', name: 'Nobelium',     mass: 259,     col: 16, row: 10, cat: 'ac', st: 'unknown' },
  { z:103, sym: 'Lr', name: 'Lawrencium',   mass: 266,     col: 17, row: 10, cat: 'ac', st: 'unknown' },
  { z:104, sym: 'Rf', name: 'Rutherfordium',mass: 267,     col:  4, row: 7, cat: 'tm', st: 'unknown' },
  { z:105, sym: 'Db', name: 'Dubnium',      mass: 268,     col:  5, row: 7, cat: 'tm', st: 'unknown' },
  { z:106, sym: 'Sg', name: 'Seaborgium',   mass: 269,     col:  6, row: 7, cat: 'tm', st: 'unknown' },
  { z:107, sym: 'Bh', name: 'Bohrium',      mass: 270,     col:  7, row: 7, cat: 'tm', st: 'unknown' },
  { z:108, sym: 'Hs', name: 'Hassium',      mass: 269,     col:  8, row: 7, cat: 'tm', st: 'unknown' },
  { z:109, sym: 'Mt', name: 'Meitnerium',   mass: 278,     col:  9, row: 7, cat: 'un', st: 'unknown' },
  { z:110, sym: 'Ds', name: 'Darmstadtium', mass: 281,     col: 10, row: 7, cat: 'un', st: 'unknown' },
  { z:111, sym: 'Rg', name: 'Roentgenium',  mass: 282,     col: 11, row: 7, cat: 'un', st: 'unknown' },
  { z:112, sym: 'Cn', name: 'Copernicium',  mass: 285,     col: 12, row: 7, cat: 'tm', st: 'unknown' },
  { z:113, sym: 'Nh', name: 'Nihonium',     mass: 286,     col: 13, row: 7, cat: 'un', st: 'unknown' },
  { z:114, sym: 'Fl', name: 'Flerovium',    mass: 289,     col: 14, row: 7, cat: 'un', st: 'unknown' },
  { z:115, sym: 'Mc', name: 'Moscovium',    mass: 290,     col: 15, row: 7, cat: 'un', st: 'unknown' },
  { z:116, sym: 'Lv', name: 'Livermorium',  mass: 293,     col: 16, row: 7, cat: 'un', st: 'unknown' },
  { z:117, sym: 'Ts', name: 'Tennessine',   mass: 294,     col: 17, row: 7, cat: 'un', st: 'unknown' },
  { z:118, sym: 'Og', name: 'Oganesson',    mass: 294,     col: 18, row: 7, cat: 'un', st: 'unknown' },
];

export const CATEGORY_COLORS = {
  am: '#ef4444', ae: '#f59e0b', tm: '#3b82f6', pm: '#06b6d4',
  ml: '#a855f7', nm: '#10b981', ha: '#14b8a6', ng: '#8b5cf6',
  la: '#ec4899', ac: '#f97316', un: '#94a3b8',
};

export const CATEGORY_LABELS = {
  am: 'Alkali metal', ae: 'Alkaline earth', tm: 'Transition metal',
  pm: 'Post-transition metal', ml: 'Metalloid', nm: 'Nonmetal',
  ha: 'Halogen', ng: 'Noble gas', la: 'Lanthanide', ac: 'Actinide', un: 'Unknown',
};

export const STATE_COLORS = {
  solid: '#64748b', liquid: '#3b82f6', gas: '#10b981', unknown: '#94a3b8',
};
